<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220217224707 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add slug to place table.';
    }

    public function up(Schema $schema): void
    {

        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE place ADD slug VARCHAR(150) NOT NULL');
        $this->addSql("UPDATE dn.place p SET p.slug = 'navaselki' WHERE p.id = 1");
        $this->addSql("UPDATE dn.place p SET p.slug = 'antanevichy' WHERE p.id = 2");
        $this->addSql("UPDATE dn.place p SET p.slug = 'celepuny-mikraraen-g-mazyr' WHERE p.id = 3");
        $this->addSql("UPDATE dn.place p SET p.slug = 'shutavichy' WHERE p.id = 4");
        $this->addSql("UPDATE dn.place p SET p.slug = 'byalko-shchyna' WHERE p.id = 5");
        $this->addSql("UPDATE dn.place p SET p.slug = 'belaya-mazyrski' WHERE p.id = 6");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zavaly' WHERE p.id = 7");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zimovishchy' WHERE p.id = 9");
        $this->addSql("UPDATE dn.place p SET p.slug = 'yarca-ka' WHERE p.id = 10");
        $this->addSql("UPDATE dn.place p SET p.slug = 'staraya-metcha' WHERE p.id = 11");
        $this->addSql("UPDATE dn.place p SET p.slug = 'barok' WHERE p.id = 12");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kazlo-shchyna' WHERE p.id = 13");
        $this->addSql("UPDATE dn.place p SET p.slug = 'babichy' WHERE p.id = 17");
        $this->addSql("UPDATE dn.place p SET p.slug = 'machul' WHERE p.id = 18");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zagoryny' WHERE p.id = 19");
        $this->addSql("UPDATE dn.place p SET p.slug = 'nisimkavichy' WHERE p.id = 20");
        $this->addSql("UPDATE dn.place p SET p.slug = 'metcha' WHERE p.id = 21");
        $this->addSql("UPDATE dn.place p SET p.slug = 'selishcha-barysa-ski' WHERE p.id = 22");
        $this->addSql("UPDATE dn.place p SET p.slug = 'merkulavichy' WHERE p.id = 23");
        $this->addSql("UPDATE dn.place p SET p.slug = 'levashy' WHERE p.id = 24");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zabroddze' WHERE p.id = 25");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vyaseya' WHERE p.id = 27");
        $this->addSql("UPDATE dn.place p SET p.slug = 'slabada' WHERE p.id = 28");
        $this->addSql("UPDATE dn.place p SET p.slug = 'davyd-garadok' WHERE p.id = 29");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gryckavichy' WHERE p.id = 30");
        $this->addSql("UPDATE dn.place p SET p.slug = 'palichnae' WHERE p.id = 31");
        $this->addSql("UPDATE dn.place p SET p.slug = 'illya' WHERE p.id = 32");
        $this->addSql("UPDATE dn.place p SET p.slug = 'shascisnopy' WHERE p.id = 33");
        $this->addSql("UPDATE dn.place p SET p.slug = 'klompiki' WHERE p.id = 34");
        $this->addSql("UPDATE dn.place p SET p.slug = 'aranchycy' WHERE p.id = 35");
        $this->addSql("UPDATE dn.place p SET p.slug = 'brusy' WHERE p.id = 36");
        $this->addSql("UPDATE dn.place p SET p.slug = 'muravanaya-ashmyanka' WHERE p.id = 37");
        $this->addSql("UPDATE dn.place p SET p.slug = 'novy-dvor' WHERE p.id = 38");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vugly' WHERE p.id = 39");
        $this->addSql("UPDATE dn.place p SET p.slug = 'pogiry' WHERE p.id = 40");
        $this->addSql("UPDATE dn.place p SET p.slug = 'macka-cy' WHERE p.id = 41");
        $this->addSql("UPDATE dn.place p SET p.slug = 'taluc' WHERE p.id = 42");
        $this->addSql("UPDATE dn.place p SET p.slug = 'belaya-lagoyski' WHERE p.id = 43");
        $this->addSql("UPDATE dn.place p SET p.slug = 'yuncavichy' WHERE p.id = 44");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gra-zhyshki' WHERE p.id = 45");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gayna' WHERE p.id = 46");
        $this->addSql("UPDATE dn.place p SET p.slug = 'karo-chyna' WHERE p.id = 48");
        $this->addSql("UPDATE dn.place p SET p.slug = 'pyanki' WHERE p.id = 49");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zasecce' WHERE p.id = 50");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gadzichava' WHERE p.id = 51");
        $this->addSql("UPDATE dn.place p SET p.slug = 'hacisla' WHERE p.id = 52");
        $this->addSql("UPDATE dn.place p SET p.slug = 'buynavichy' WHERE p.id = 53");
        $this->addSql("UPDATE dn.place p SET p.slug = 'karpavichy' WHERE p.id = 54");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vileyka' WHERE p.id = 55");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zaazer-e' WHERE p.id = 57");
        $this->addSql("UPDATE dn.place p SET p.slug = 'karaneva' WHERE p.id = 58");
        $this->addSql("UPDATE dn.place p SET p.slug = 'stayki' WHERE p.id = 59");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zalesse' WHERE p.id = 60");
        $this->addSql("UPDATE dn.place p SET p.slug = 'trasechanyaty' WHERE p.id = 61");
        $this->addSql("UPDATE dn.place p SET p.slug = 'saroki' WHERE p.id = 62");
        $this->addSql("UPDATE dn.place p SET p.slug = 'studzera-shchyna' WHERE p.id = 63");
        $this->addSql("UPDATE dn.place p SET p.slug = 'valoviki' WHERE p.id = 64");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vyalikiya-kazly' WHERE p.id = 65");
        $this->addSql("UPDATE dn.place p SET p.slug = 'byalya-shchyna' WHERE p.id = 66");
        $this->addSql("UPDATE dn.place p SET p.slug = 'alho-ka' WHERE p.id = 67");
        $this->addSql("UPDATE dn.place p SET p.slug = 'ashmyany' WHERE p.id = 68");
        $this->addSql("UPDATE dn.place p SET p.slug = 'lasi' WHERE p.id = 69");
        $this->addSql("UPDATE dn.place p SET p.slug = 'markavichy' WHERE p.id = 70");
        $this->addSql("UPDATE dn.place p SET p.slug = 'ra-dastava' WHERE p.id = 71");
        $this->addSql("UPDATE dn.place p SET p.slug = 'byasedavichy' WHERE p.id = 72");
        $this->addSql("UPDATE dn.place p SET p.slug = 'lambava' WHERE p.id = 73");
        $this->addSql("UPDATE dn.place p SET p.slug = 'varatyn' WHERE p.id = 74");
        $this->addSql("UPDATE dn.place p SET p.slug = 'varvara-ka' WHERE p.id = 75");
        $this->addSql("UPDATE dn.place p SET p.slug = 'asarevichy' WHERE p.id = 76");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gudagay' WHERE p.id = 77");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kotchyna' WHERE p.id = 78");
        $this->addSql("UPDATE dn.place p SET p.slug = 'valeykavichy' WHERE p.id = 79");
        $this->addSql("UPDATE dn.place p SET p.slug = 'meshychy' WHERE p.id = 80");
        $this->addSql("UPDATE dn.place p SET p.slug = 'ivanka-shchyna' WHERE p.id = 81");
        $this->addSql("UPDATE dn.place p SET p.slug = 'plastok' WHERE p.id = 82");
        $this->addSql("UPDATE dn.place p SET p.slug = 'yaminsk' WHERE p.id = 83");
        $this->addSql("UPDATE dn.place p SET p.slug = 'lyuban' WHERE p.id = 84");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zabalac' WHERE p.id = 85");
        $this->addSql("UPDATE dn.place p SET p.slug = 'rachen' WHERE p.id = 86");
        $this->addSql("UPDATE dn.place p SET p.slug = 'sosny' WHERE p.id = 87");
        $this->addSql("UPDATE dn.place p SET p.slug = 'shypilavichy' WHERE p.id = 88");
        $this->addSql("UPDATE dn.place p SET p.slug = 'yushkavichy' WHERE p.id = 89");
        $this->addSql("UPDATE dn.place p SET p.slug = 'dembrava' WHERE p.id = 90");
        $this->addSql("UPDATE dn.place p SET p.slug = 'talmachava' WHERE p.id = 91");
        $this->addSql("UPDATE dn.place p SET p.slug = 'sinichyna' WHERE p.id = 92");
        $this->addSql("UPDATE dn.place p SET p.slug = 'valosavichy' WHERE p.id = 93");
        $this->addSql("UPDATE dn.place p SET p.slug = 'konkavichy' WHERE p.id = 94");
        $this->addSql("UPDATE dn.place p SET p.slug = 'haromcy' WHERE p.id = 95");
        $this->addSql("UPDATE dn.place p SET p.slug = 'asavec' WHERE p.id = 96");
        $this->addSql("UPDATE dn.place p SET p.slug = 'simanovichy' WHERE p.id = 97");
        $this->addSql("UPDATE dn.place p SET p.slug = 'prusy' WHERE p.id = 98");
        $this->addSql("UPDATE dn.place p SET p.slug = 'svislach' WHERE p.id = 99");
        $this->addSql("UPDATE dn.place p SET p.slug = 'rama-shkava' WHERE p.id = 100");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kalchu-ny' WHERE p.id = 101");
        $this->addSql("UPDATE dn.place p SET p.slug = 'syalec' WHERE p.id = 102");
        $this->addSql("UPDATE dn.place p SET p.slug = 'baloty' WHERE p.id = 103");
        $this->addSql("UPDATE dn.place p SET p.slug = 'galavenchycy' WHERE p.id = 104");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gory' WHERE p.id = 105");
        $this->addSql("UPDATE dn.place p SET p.slug = 'krycha' WHERE p.id = 106");
        $this->addSql("UPDATE dn.place p SET p.slug = 'dubrova' WHERE p.id = 107");
        $this->addSql("UPDATE dn.place p SET p.slug = 'senkava' WHERE p.id = 108");
        $this->addSql("UPDATE dn.place p SET p.slug = 'balashevichy' WHERE p.id = 109");
        $this->addSql("UPDATE dn.place p SET p.slug = 'babirova' WHERE p.id = 110");
        $this->addSql("UPDATE dn.place p SET p.slug = 'garadzec' WHERE p.id = 111");
        $this->addSql("UPDATE dn.place p SET p.slug = 'akuneva' WHERE p.id = 112");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vele-shchyna' WHERE p.id = 113");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kazlovichy' WHERE p.id = 114");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vyarechcha' WHERE p.id = 115");
        $this->addSql("UPDATE dn.place p SET p.slug = 'nyamoyta' WHERE p.id = 116");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gubina' WHERE p.id = 117");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vaclavova' WHERE p.id = 118");
        $this->addSql("UPDATE dn.place p SET p.slug = 'shupeni' WHERE p.id = 119");
        $this->addSql("UPDATE dn.place p SET p.slug = 'maskalyanyaty' WHERE p.id = 120");
        $this->addSql("UPDATE dn.place p SET p.slug = 'cvecina' WHERE p.id = 121");
        $this->addSql("UPDATE dn.place p SET p.slug = 'lyady' WHERE p.id = 122");
        $this->addSql("UPDATE dn.place p SET p.slug = 'sipi-shchava' WHERE p.id = 123");
        $this->addSql("UPDATE dn.place p SET p.slug = 'usveya' WHERE p.id = 124");
        $this->addSql("UPDATE dn.place p SET p.slug = 'grabava' WHERE p.id = 125");
        $this->addSql("UPDATE dn.place p SET p.slug = 'acminava' WHERE p.id = 126");
        $this->addSql("UPDATE dn.place p SET p.slug = 'bystryca' WHERE p.id = 127");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kuklichy' WHERE p.id = 128");
        $this->addSql("UPDATE dn.place p SET p.slug = 'sinki' WHERE p.id = 129");
        $this->addSql("UPDATE dn.place p SET p.slug = 'barodzichy' WHERE p.id = 130");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kanyuhi' WHERE p.id = 131");
        $this->addSql("UPDATE dn.place p SET p.slug = 'razhanka' WHERE p.id = 132");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gorka' WHERE p.id = 133");
        $this->addSql("UPDATE dn.place p SET p.slug = 'buyki' WHERE p.id = 134");
        $this->addSql("UPDATE dn.place p SET p.slug = 'syadzelniki' WHERE p.id = 135");
        $this->addSql("UPDATE dn.place p SET p.slug = 'semerniki' WHERE p.id = 136");
        $this->addSql("UPDATE dn.place p SET p.slug = 'giry' WHERE p.id = 137");
        $this->addSql("UPDATE dn.place p SET p.slug = 'staraya-rudnya' WHERE p.id = 138");
        $this->addSql("UPDATE dn.place p SET p.slug = 'padarosk' WHERE p.id = 139");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zagor-e' WHERE p.id = 140");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zhmurnae' WHERE p.id = 141");
        $this->addSql("UPDATE dn.place p SET p.slug = 'yankavichy' WHERE p.id = 142");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kaha-navichy' WHERE p.id = 143");
        $this->addSql("UPDATE dn.place p SET p.slug = 'ty-shkavichy' WHERE p.id = 145");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kramno' WHERE p.id = 146");
        $this->addSql("UPDATE dn.place p SET p.slug = 'velyamo-vichy' WHERE p.id = 147");
        $this->addSql("UPDATE dn.place p SET p.slug = 'sinkevichy' WHERE p.id = 148");
        $this->addSql("UPDATE dn.place p SET p.slug = 'skibichy' WHERE p.id = 149");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kolansk' WHERE p.id = 150");
        $this->addSql("UPDATE dn.place p SET p.slug = 'ugalec' WHERE p.id = 151");
        $this->addSql("UPDATE dn.place p SET p.slug = 'berazlyany' WHERE p.id = 152");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gortal' WHERE p.id = 153");
        $this->addSql("UPDATE dn.place p SET p.slug = 'dzyamenichy' WHERE p.id = 154");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vyalikaya-gac' WHERE p.id = 155");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zaluzze' WHERE p.id = 156");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gru-shka' WHERE p.id = 157");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zamshany' WHERE p.id = 158");
        $this->addSql("UPDATE dn.place p SET p.slug = 'radchyck' WHERE p.id = 159");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kraglevichy' WHERE p.id = 160");
        $this->addSql("UPDATE dn.place p SET p.slug = 'lyaha-cy' WHERE p.id = 161");
        $this->addSql("UPDATE dn.place p SET p.slug = 'batchy' WHERE p.id = 162");
        $this->addSql("UPDATE dn.place p SET p.slug = 'rechyca' WHERE p.id = 163");
        $this->addSql("UPDATE dn.place p SET p.slug = 'la-darazh' WHERE p.id = 164");
        $this->addSql("UPDATE dn.place p SET p.slug = 'ga-rylchycy' WHERE p.id = 166");
        $this->addSql("UPDATE dn.place p SET p.slug = 'sarachy' WHERE p.id = 167");
        $this->addSql("UPDATE dn.place p SET p.slug = 'morach' WHERE p.id = 168");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gulyaeva' WHERE p.id = 169");
        $this->addSql("UPDATE dn.place p SET p.slug = 'babki' WHERE p.id = 170");
        $this->addSql("UPDATE dn.place p SET p.slug = 'palazhevichy' WHERE p.id = 171");
        $this->addSql("UPDATE dn.place p SET p.slug = 'palazhevichy' WHERE p.id = 172");
        $this->addSql("UPDATE dn.place p SET p.slug = 'selishcha-slucki' WHERE p.id = 173");
        $this->addSql("UPDATE dn.place p SET p.slug = 'stary-ya-daro-gi' WHERE p.id = 174");
        $this->addSql("UPDATE dn.place p SET p.slug = 'pastavichy' WHERE p.id = 175");
        $this->addSql("UPDATE dn.place p SET p.slug = 'lan' WHERE p.id = 176");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vynishchy' WHERE p.id = 177");
        $this->addSql("UPDATE dn.place p SET p.slug = 'shchytkavichy' WHERE p.id = 178");
        $this->addSql("UPDATE dn.place p SET p.slug = 'rymashy' WHERE p.id = 179");
        $this->addSql("UPDATE dn.place p SET p.slug = 'andrushy' WHERE p.id = 180");
        $this->addSql("UPDATE dn.place p SET p.slug = 'pry-synak' WHERE p.id = 181");
        $this->addSql("UPDATE dn.place p SET p.slug = 'chyzhaha' WHERE p.id = 182");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gorki' WHERE p.id = 183");
        $this->addSql("UPDATE dn.place p SET p.slug = 'charnagradz' WHERE p.id = 184");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kapla-ncy' WHERE p.id = 185");
        $this->addSql("UPDATE dn.place p SET p.slug = 'skirmantava' WHERE p.id = 186");
        $this->addSql("UPDATE dn.place p SET p.slug = 'la-nica' WHERE p.id = 187");
        $this->addSql("UPDATE dn.place p SET p.slug = 'levanova' WHERE p.id = 188");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vyalyacichy' WHERE p.id = 189");
        $this->addSql("UPDATE dn.place p SET p.slug = 'navayanchyna' WHERE p.id = 190");
        $this->addSql("UPDATE dn.place p SET p.slug = 'trayana-ka' WHERE p.id = 191");
        $this->addSql("UPDATE dn.place p SET p.slug = 'myadzel-stary' WHERE p.id = 192");
        $this->addSql("UPDATE dn.place p SET p.slug = 'ni-ki' WHERE p.id = 193");
        $this->addSql("UPDATE dn.place p SET p.slug = 'hodcy' WHERE p.id = 194");
        $this->addSql("UPDATE dn.place p SET p.slug = 'markava' WHERE p.id = 195");
        $this->addSql("UPDATE dn.place p SET p.slug = 'garadok' WHERE p.id = 196");
        $this->addSql("UPDATE dn.place p SET p.slug = 'stayalava' WHERE p.id = 197");
        $this->addSql("UPDATE dn.place p SET p.slug = 'stary-vostra' WHERE p.id = 198");
        $this->addSql("UPDATE dn.place p SET p.slug = 'arehava' WHERE p.id = 199");
        $this->addSql("UPDATE dn.place p SET p.slug = 'bukcha' WHERE p.id = 200");
        $this->addSql("UPDATE dn.place p SET p.slug = 'mazali' WHERE p.id = 201");
        $this->addSql("UPDATE dn.place p SET p.slug = 'darasino' WHERE p.id = 202");
        $this->addSql("UPDATE dn.place p SET p.slug = 'chamyaryn' WHERE p.id = 203");
        $this->addSql("UPDATE dn.place p SET p.slug = 'lyaskavichy' WHERE p.id = 204");
        $this->addSql("UPDATE dn.place p SET p.slug = 'lyaskavichy' WHERE p.id = 205");
        $this->addSql("UPDATE dn.place p SET p.slug = 'zagoryny' WHERE p.id = 206");
        $this->addSql("UPDATE dn.place p SET p.slug = 'glinica' WHERE p.id = 207");
        $this->addSql("UPDATE dn.place p SET p.slug = 'matnyavichy' WHERE p.id = 208");
        $this->addSql("UPDATE dn.place p SET p.slug = 'lyubavichy' WHERE p.id = 209");
        $this->addSql("UPDATE dn.place p SET p.slug = 'prybalavichy' WHERE p.id = 210");
        $this->addSql("UPDATE dn.place p SET p.slug = 'ivanava-slabada' WHERE p.id = 211");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kapatkevichy' WHERE p.id = 212");
        $this->addSql("UPDATE dn.place p SET p.slug = 'pagost' WHERE p.id = 213");
        $this->addSql("UPDATE dn.place p SET p.slug = 'verasnica' WHERE p.id = 214");
        $this->addSql("UPDATE dn.place p SET p.slug = 'shylavichy' WHERE p.id = 215");
        $this->addSql("UPDATE dn.place p SET p.slug = 'rudnya-nisimkavickaya' WHERE p.id = 216");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vuc' WHERE p.id = 217");
        $this->addSql("UPDATE dn.place p SET p.slug = 'ivolsk' WHERE p.id = 218");
        $this->addSql("UPDATE dn.place p SET p.slug = 'tonezh' WHERE p.id = 219");
        $this->addSql("UPDATE dn.place p SET p.slug = 'glushkavichy' WHERE p.id = 220");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kashevichy' WHERE p.id = 221");
        $this->addSql("UPDATE dn.place p SET p.slug = 'chyrvonaya-slabada' WHERE p.id = 222");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vyalikiya-zimovishchy' WHERE p.id = 223");
        $this->addSql("UPDATE dn.place p SET p.slug = 'vozemlya' WHERE p.id = 224");
        $this->addSql("UPDATE dn.place p SET p.slug = 'sasno-ka' WHERE p.id = 225");
        $this->addSql("UPDATE dn.place p SET p.slug = 'novaya-dubrova' WHERE p.id = 226");
        $this->addSql("UPDATE dn.place p SET p.slug = 'nyastanavichy' WHERE p.id = 227");
        $this->addSql("UPDATE dn.place p SET p.slug = 'liplyany' WHERE p.id = 228");
        $this->addSql("UPDATE dn.place p SET p.slug = 'makanavichy' WHERE p.id = 229");
        $this->addSql("UPDATE dn.place p SET p.slug = 'asina-ka' WHERE p.id = 230");
        $this->addSql("UPDATE dn.place p SET p.slug = 'gackoe' WHERE p.id = 231");
        $this->addSql("UPDATE dn.place p SET p.slug = 'palesse' WHERE p.id = 232");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kanatop' WHERE p.id = 233");
        $this->addSql("UPDATE dn.place p SET p.slug = 'budki' WHERE p.id = 234");
        $this->addSql("UPDATE dn.place p SET p.slug = 'agarodniki' WHERE p.id = 235");
        $this->addSql("UPDATE dn.place p SET p.slug = 'astrazhanka' WHERE p.id = 236");
        $this->addSql("UPDATE dn.place p SET p.slug = 'padgalle' WHERE p.id = 237");
        $this->addSql("UPDATE dn.place p SET p.slug = 'budki' WHERE p.id = 238");
        $this->addSql("UPDATE dn.place p SET p.slug = 'hilchycy' WHERE p.id = 239");
        $this->addSql("UPDATE dn.place p SET p.slug = 'kurycichy' WHERE p.id = 240");
        $this->addSql("UPDATE dn.place p SET p.slug = 'mazyr' WHERE p.id = 241");
        $this->addSql("UPDATE dn.place p SET p.slug = 'krasnica' WHERE p.id = 242");
        $this->addSql("UPDATE dn.place p SET p.slug = 'pratasy' WHERE p.id = 243");
        $this->addSql("UPDATE dn.place p SET p.slug = 'da-galesse' WHERE p.id = 244");
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE place DROP slug');
    }
}
